import  WhatsApp  from "./whtaup.png"
import headingImg from "./EEA.png"
import twinRider from "./Twin-Riders.png"
import sliderImg from "./ADULT-DOUBLE-01.png"
import desertImg from "./desert_ex.jpg"
import singleImg from "./Single-Riders.png"
import adventureImg from "./Adventure-TRNS.png"
import desertEx from "./desert_ex.jpg"
import galleryImg from "./gallery_m1.jpg"
import whiteBg from "./white_bg_02.jpg"
import logo from "./logo_images.png"
import sharma320 from "./SHARMAX-hummer-320-CC.png"
import sharma180 from "./SHARMAX-ATV-CROSS-180-CC.png"
import kymko250 from "./kymko-mxu-250-cc.png"
import polaris1000 from "./POLARIS-RZR-1000-CC.png"
import sharmaATV250 from "./SHARMAX-ATV-CROSS-180-CC.png"
import bluebuggy from "./ADULT-DOUBLE-03.png"
import sharmaatv250 from "./SHARMAX-ATV-250-CC.png"
import cannam1000 from "./cannam.png"
import cannam4 from "./cannam4.png"
import road1 from "./1.png"
import bike from "./bike.png"
import road2 from "./other_3.png"
import great from "./greate_deal.png"
import half from "./half_celcal.png"
import last from "./last.jpg"
import user from "./user.jpg"
import desert from "./desertxtrem_1.png"
import desert1 from "./desert1.jpg"
import desert2 from "./desert2.jpg"
import desert3 from "./desert3.png"
import desert4 from "./desert4.png"
import desert5 from "./desert5.jpg"
import favorite from "./favorute1.jpg"
import favorite1 from "./favorate2.jpg"
import favorite2 from "./favorate3.png"
import tickIcon from "./Tick-icon.png"
import cardImage from "./POLARIS-RZR-1000-CC.png"
import banner1 from "./banner1.jpg"


// --------------------------------------------------------------

import Canam1 from "./slid/canam1000/cana1.webp"
import canam from "./slid/canam1000/cana.jpg"
import Canam2 from "./slid/canam1000/cana2.webp"
import Canam3 from "./slid/canam1000/cana3.jpg"
import Canam4 from "./slid/canam1000/cana4.webp"
import Canam5 from "./slid/canam1000/cana5.jpg"
import dart1 from "./slid/Dirt_bike_280/dart1.jpg"
import dart2 from "./slid/Dirt_bike_280/dart2.jpg"
import dart3 from "./slid/Dirt_bike_280/dart3.jpg"
import dart4 from "./slid/Dirt_bike_280/dart4.webp"
import dart5 from "./slid/Dirt_bike_280/dart5.webp"
import kymko1 from "./slid/KYMKO_MXU/kymko1.jpg"
import kymko2 from "./slid/KYMKO_MXU/kymko2.jpg"
import kymko3 from "./slid/KYMKO_MXU/kymko3.png"
import kymko4 from "./slid/KYMKO_MXU/kymko4.webp"
import kymko5 from "./slid/KYMKO_MXU/kymko5.png"
import pol from "./slid/POLARIS-4/pol.jpg"
import pol1 from "./slid/POLARIS-4/pol1.webp"
import pol2 from "./slid/POLARIS-4/pol2.jpeg"
import pol3 from "./slid/POLARIS-4/pol3.jpg"
import pol4 from "./slid/POLARIS-4/pol4.jpg"
import pol5 from "./slid/POLARIS-4/pol5.jpg"
import pol6 from "./slid/POLARIS-4/pol6.jpg"
import pole from "./slid/Polaris-2/pole.jpg"
import pole1 from "./slid/Polaris-2/pole1.jpg"
import pole2 from "./slid/Polaris-2/pole2.jpg"
import pole3 from "./slid/Polaris-2/pole3.jpg"
import pole4 from "./slid/Polaris-2/pole4.jpg"
import pole5 from "./slid/Polaris-2/pole5.jpg"
import yam1 from "./slid/Yamaha450-CC/yam1.png"
import yam2 from "./slid/Yamaha450-CC/yam2.jpeg"
import yam3 from "./slid/Yamaha450-CC/yam3.jpg"
import yam4 from "./slid/Yamaha450-CC/yam4.webp"
import yrapto1 from "./slid/YAMAHA-700-CC/yrapto1.jpg"
import yrapto2 from "./slid/YAMAHA-700-CC/yrapto2.jpg"
import yrapto3 from "./slid/YAMAHA-700-CC/yrapto3.jpg"
import yrapto4 from "./slid/YAMAHA-700-CC/yrapto4.jpg"
import yrapto5 from "./slid/YAMAHA-700-CC/yrapto5.jpg"
import shar1 from "./slid/SHARMAX/shar1.webp"
import shar2 from "./slid/SHARMAX/shar2.jpg"
import shar3 from "./slid/SHARMAX/shar3.jpg"
import shar4 from "./slid/SHARMAX/shar4.webp"
import polar1 from "./slid/POLARIS-570-CC/57pol1.jpg"
import polar2 from "./slid/POLARIS-570-CC/57pol2.webp"
import polar3 from "./slid/POLARIS-570-CC/57pol3.jpg"
import polar4 from "./slid/POLARIS-570-CC/57pol4.webp"
import deal from "./deals.png"
import sharmax1 from "./slid/sharmax-180/sharm1.jpeg"
import sharmax2 from "./slid/sharmax-180/sharm2.jpg"
import sharmax3 from "./slid/sharmax-180/sharm3.jpeg"
import sharmax4 from "./slid/sharmax-180/sharm4.jpeg"
import shramax5 from "./slid/sharmax-180/sharm5.jpg"










export {banner1,sharmax1,sharmax2,sharmax3,sharmax4,shramax5,polar1,polar2,polar3,deal,polar4,shar1,shar2,shar3,shar4,yrapto1,yrapto2,yrapto3,yrapto4,yrapto5,yam1,yam2,yam3,yam4,pole,pole1, pole2,pole3,pole4,pole5,pol,pol1, pol2,pol3,pol4,pol5,pol6,kymko1,kymko2,kymko3,kymko4,kymko5,dart1,dart2,dart3,dart4, dart5,canam,Canam1,Canam2,Canam3,Canam4,Canam5,kymko250,cardImage,favorite,favorite1,favorite2, desert,desert1,desert2,desert3,desert4,desert5,tickIcon,headingImg,last,sharma320,user, road1,half ,great ,bike, road2, cannam1000,WhatsApp, cannam4,sharma180, bluebuggy ,polaris1000,sharmaATV250,sharmaatv250 ,twinRider, sliderImg, desertImg, singleImg, adventureImg, desertEx,logo, galleryImg,whiteBg, }